name: deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Login Heroku
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      
      - name: Add Heroku backend remote
        run: heroku git:remote -a $HEROKU_BACKEND_APP_NAME
        env:
          HEROKU_BACKEND_APP_NAME: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
      
      - name: Push backend to Heroku
        run: git subtree push --prefix backend heroku main
      
      - name: Add Heroku frontend remote
        run: heroku git:remote -a $HEROKU_FRONTEND_APP_NAME
        env:
          HEROKU_FRONTEND_APP_NAME: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
      
      - name: Push frontend to Heroku
        run: git subtree push --prefix frontend heroku main

      
